"""Export a bounded, read-only OpenAlex sample as static website assets.

Run from the repository root: python scripts/export_preview.py
Requires psycopg 3. Uses OPENALEX_DSN or the repository's default connection.
This is an explicit maintenance command, never part of the Franklin build.
"""
from __future__ import annotations

import argparse
import csv
import html
import io
import json
import os
from pathlib import Path
import subprocess

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

SITE = Path(__file__).resolve().parents[1]
REPO = SITE
COLUMNS = {
    "works": ["id", "title", "publication_year", "type", "language", "cited_by_count",
              "primary_location_source_id", "primary_topic_id", "doi", "is_retracted"],
    "authors": ["id", "display_name", "orcid", "works_count", "cited_by_count"],
    "institutions": ["id", "display_name", "country_code", "type", "ror"],
    "sources": ["id", "display_name", "type", "issn_l", "is_oa", "works_count"],
    "topics": ["id", "display_name", "subfield_display_name", "field_display_name", "domain_display_name"],
    "works_authorships": ["work_id", "author_id", "author_position", "is_corresponding"],
    "works_authorship_institutions": ["work_id", "author_id", "institution_id"],
    "works_topics": ["work_id", "topic_id", "score", "is_primary"],
    "works_open_access": ["work_id", "is_oa", "oa_status", "oa_url"],
    "works_referenced_works": ["work_id", "referenced_work_id"],
}
DESCRIPTIONS = {
    "works": "A bounded block sample of scholarly works. Open a record to follow its relationships.",
    "authors": "Author records resolved from the sampled works' authorships. Counts describe each author in the database, not this sample.",
    "institutions": "Institutions resolved from the sampled works' affiliation links.",
    "sources": "Primary publication sources resolved from the sampled works. Works counts describe the source in the database.",
    "topics": "Primary and additional topics resolved from the sampled works, with their classification hierarchy.",
    "works_authorships": "Authorship links for the sampled works. One work can have many authors.",
    "works_authorship_institutions": "Affiliations linking a work and author to an institution. Authors can have multiple affiliations.",
    "works_topics": "Topic assignments and scores for the sampled works; the primary assignment is flagged.",
    "works_open_access": "Open-access status observed in the loaded dataset, not necessarily at publication.",
    "works_referenced_works": "At most 12 reference links per sampled work, ordered by referenced ID. Target works are not exported unless already in the sample.",
}


def related(conn, table, key, values):
    """Bound relationship reads and fail rather than silently truncate them."""
    query = sql.SQL("SELECT {} FROM openalex.{} WHERE {} = ANY(%s) ORDER BY {} LIMIT 10001").format(
        sql.SQL(", ").join(map(sql.Identifier, COLUMNS[table])), sql.Identifier(table),
        sql.Identifier(key), sql.SQL(", ").join(map(sql.Identifier, COLUMNS[table][:2])),
    )
    rows = conn.execute(query, (sorted(set(v for v in values if v)),)).fetchall()
    if len(rows) > 10000:
        raise RuntimeError(f"{table} exceeds the preview size bound; choose a smaller work sample")
    return rows


def ids(rows, key):
    return [row[key] for row in rows if row[key]]


def esc(value):
    return html.escape(str(value), quote=True).replace("{", "&#123;").replace("}", "&#125;")


def generate_fragment(dataset):
    """Emit a real static table before adding optional browser interaction."""
    works = dataset["tables"]["works"]["rows"]
    author_count = len(dataset["tables"]["authors"]["rows"])
    source_count = len(dataset["tables"]["sources"]["rows"])
    exported = dataset["metadata"]["exported_at_utc"]
    body = []
    for row in works:
        body.append(f'<tr><td><a href="{esc(row["id"])}">{esc(row["id"].rsplit("/", 1)[-1])} ↗</a></td>'
                    f'<td>{esc(row["title"] or "Untitled")}</td><td>{esc(row["publication_year"] or "—")}</td>'
                    f'<td>{esc(row["type"] or "—")}</td><td>{esc(row["cited_by_count"])}</td></tr>')
    # Escape raw HTML delimiters in JSON so source metadata cannot end the script.
    payload = json.dumps(dataset, ensure_ascii=True, indent=1).replace("<", "\\u003c").replace("&", "\\u0026")
    # Franklin interprets double braces even inside raw HTML includes.
    payload = payload.replace("{{", "\\u007b\\u007b").replace("}}", "\\u007d\\u007d")
    return f'''<!-- Generated by scripts/export_preview.py. Refresh with that command. -->
<div class="preview-summary" aria-label="Export summary">
  <div><strong>{len(works)}</strong><span>sampled works</span></div>
  <div><strong>{author_count}</strong><span>linked authors</span></div>
  <div><strong>{source_count}</strong><span>publication sources</span></div>
  <div><strong>{len(dataset["tables"])}</strong><span>tables to explore</span></div>
</div>
<p class="preview-provenance"><span class="signal-dot"></span> Actual PostgreSQL records · Exported <time>{esc(exported)}</time> · Static, bounded sample</p>
<div class="preview-controls" hidden>
  <label>Table<select id="preview-table">{''.join(f'<option value="{name}">{name} ({len(data["rows"]):,})</option>' for name, data in dataset["tables"].items())}</select></label>
  <label class="preview-search-label">Search this sample<input id="preview-search" type="search" placeholder="Search titles, IDs, names…" autocomplete="off"></label>
  <button id="preview-reset" class="preview-secondary" type="button">Reset</button>
</div>
<section class="preview-browser" aria-labelledby="preview-table-title">
  <div class="preview-table-toolbar"><div><h2 id="preview-table-title">works</h2></div><a id="preview-csv" class="preview-secondary" href="/assets/preview/works.csv" download>Download CSV ↓</a></div>
  <p id="preview-table-description">{esc(DESCRIPTIONS['works'])}</p>
  <div class="preview-table-scroll" tabindex="0" role="region" aria-label="Dataset sample table"><table id="preview-records"><caption class="sr-only">Static sample of OpenAlex works</caption><thead><tr><th scope="col">id</th><th scope="col">title</th><th scope="col">publication_year</th><th scope="col">type</th><th scope="col">cited_by_count</th></tr></thead><tbody>{''.join(body)}</tbody></table></div>
  <div class="preview-pagination" hidden><p id="preview-count" role="status" aria-live="polite"></p><div><button id="preview-prev" class="preview-secondary" type="button">← Previous</button><button id="preview-next" class="preview-secondary" type="button">Next →</button></div></div>
</section>
<section id="preview-detail" class="preview-detail" aria-labelledby="preview-detail-title" hidden></section>
<details class="preview-export-note"><summary>How this sample was exported</summary><p>{esc(dataset['metadata']['sampling'])}</p><p>Source release label: {esc(dataset['metadata']['snapshot_release'])}. {esc(dataset['metadata']['snapshot_release_basis'])}</p><p>{esc(dataset['metadata']['scope'])} Reference links are capped at 12 per work. The stored publication metadata is unchanged; only selected columns and relationships are exported.</p></details>
<script type="application/json" id="preview-dataset">{payload}</script>
'''


def generate_catalog(dataset):
    items = []
    for name, item in dataset["catalog"].items():
        estimate = "Unknown" if item["estimated_rows"] is None else f'≈ {item["estimated_rows"]:,}'
        columns = ''.join(f'<tr><th scope="row">{esc(c["name"])}</th><td>{esc(c["type"])}</td></tr>' for c in item["columns"])
        items.append(f'<details class="catalog-item"><summary><span>{esc(name)}</span><span class="catalog-estimate">{estimate}</span></summary><div class="catalog-columns"><p>{len(item["columns"])} columns · PostgreSQL types</p><table><caption class="sr-only">Columns in {esc(name)}</caption><thead><tr><th scope="col">Column</th><th scope="col">Type</th></tr></thead><tbody>{columns}</tbody></table></div></details>')
    return '<!-- Generated by scripts/export_preview.py -->\n<div class="catalog-grid">' + ''.join(items) + '</div>\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=80, help="Number of works (1–200)")
    parser.add_argument("--seed", type=int, default=20260910)
    parser.add_argument("--snapshot-release", default="2026-03-30", help="Operator-supplied source release label")
    parser.add_argument("--render-only", action="store_true", help="Regenerate HTML/CSVs from the saved JSON without connecting to PostgreSQL")
    args = parser.parse_args()
    if args.render_only:
        write_outputs(json.loads((SITE / "assets/preview/dataset.json").read_text(encoding="utf-8")))
        return
    if not 1 <= args.limit <= 200:
        parser.error("--limit must be between 1 and 200")
    dsn = os.environ.get("OPENALEX_DSN", "dbname=openalex user=simone host=localhost")
    # The transaction and connection defaults both enforce read-only access.
    with psycopg.connect(dsn, connect_timeout=5, row_factory=dict_row,
                         options="-c default_transaction_read_only=on -c statement_timeout=20000 -c lock_timeout=2000") as conn:
        conn.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY")
        exported = conn.execute("SELECT timezone('UTC', transaction_timestamp()) AS exported").fetchone()["exported"].isoformat(timespec="seconds") + "Z"
        query = sql.SQL("SELECT {} FROM openalex.works TABLESAMPLE SYSTEM (0.0001) REPEATABLE (%s) ORDER BY id LIMIT %s").format(sql.SQL(", ").join(map(sql.Identifier, COLUMNS["works"])))
        rows = {"works": conn.execute(query, (args.seed, args.limit)).fetchall()}
        if not rows["works"]:
            raise RuntimeError("Block sample returned no works; choose another --seed")
        work_ids = ids(rows["works"], "id")
        for table in ["works_authorships", "works_authorship_institutions", "works_topics", "works_open_access"]:
            rows[table] = related(conn, table, "work_id", work_ids)
        rows["authors"] = related(conn, "authors", "id", ids(rows["works_authorships"], "author_id"))
        rows["institutions"] = related(conn, "institutions", "id", ids(rows["works_authorship_institutions"], "institution_id"))
        rows["sources"] = related(conn, "sources", "id", ids(rows["works"], "primary_location_source_id"))
        rows["topics"] = related(conn, "topics", "id", ids(rows["works_topics"], "topic_id") + ids(rows["works"], "primary_topic_id"))
        rows["works_referenced_works"] = conn.execute("""
            SELECT selected.work_id, r.referenced_work_id
            FROM unnest(%s::text[]) AS selected(work_id)
            CROSS JOIN LATERAL (
                SELECT referenced_work_id FROM openalex.works_referenced_works
                WHERE work_id = selected.work_id ORDER BY referenced_work_id LIMIT 12
            ) AS r ORDER BY selected.work_id, r.referenced_work_id
        """, (work_ids,)).fetchall()
        inventory = conn.execute("""
            SELECT c.relname AS table_name,
                   CASE WHEN c.reltuples >= 0 THEN c.reltuples::bigint END AS estimated_rows,
                   a.attname AS column_name, format_type(a.atttypid, a.atttypmod) AS sql_type
            FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            WHERE n.nspname = 'openalex' AND c.relkind = 'r'
              AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY c.relname, a.attnum
        """).fetchall()
    catalog = {}
    for entry in inventory:
        name = entry["table_name"]
        item = catalog.setdefault(name, {"estimated_rows": entry["estimated_rows"], "columns": []})
        item["columns"].append({"name": entry["column_name"], "type": entry["sql_type"]})
    dataset = {
        "metadata": {
            "exported_at_utc": exported,
            "source": "Local PostgreSQL database, openalex schema",
            "snapshot_release": args.snapshot_release,
            "snapshot_release_basis": "Operator-supplied label based on the local snapshot RELEASE_NOTES.txt; database has no built-in release marker.",
            "repository_url": "https://github.com/science-as-data/website",
            "repository_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip(),
            "sampling": f"TABLESAMPLE SYSTEM (0.0001) REPEATABLE ({args.seed}), then ORDER BY id LIMIT {args.limit}. A bounded block sample, not a representative research sample.",
            "sampling_sql": query.as_string() % (args.seed, args.limit),
            "reference_limit_per_work": 12,
            "row_estimate_source": "pg_class.reltuples; planner estimates, not exact counts",
            "scope": "Selected bibliographic columns only; related entity lookups may be unresolved; reference targets are not recursively exported.",
        },
        "tables": {name: {"columns": COLUMNS[name], "description": DESCRIPTIONS[name], "rows": rows[name]} for name in COLUMNS},
        "catalog": catalog,
    }
    write_outputs(dataset)


def write_outputs(dataset):
    # Assemble every output before writing; no database credentials are included.
    outputs = {SITE / "assets/preview/dataset.json": json.dumps(dataset, ensure_ascii=False, indent=2) + "\n",
               SITE / "_layout/dataset-preview.html": generate_fragment(dataset),
               SITE / "_layout/dataset-catalog.html": generate_catalog(dataset)}
    for table, data in dataset["tables"].items():
        stream = io.StringIO(newline="")
        writer = csv.DictWriter(stream, fieldnames=data["columns"])
        writer.writeheader()
        writer.writerows(data["rows"])
        outputs[SITE / f"assets/preview/{table}.csv"] = stream.getvalue()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(json.dumps({"exported": dataset["metadata"]["exported_at_utc"],
                      "rows": {name: len(data["rows"]) for name, data in dataset["tables"].items()},
                      "catalog_tables": len(dataset["catalog"])}, indent=2))


if __name__ == "__main__":
    main()
